export const SET_TASKS_LIST = 'TASKS/SET_TASKS_LIST';
export const ADD_TASK_TO_STATE = 'TASKS/ADD_TASK_TO_STATE';
export const CHANGE_DONE = 'TASKS/CHANGE_DONE';
export const DELETE_TASK_FROM_STATE = 'TASKS/DELETE_TASK_FROM_STATE';
